services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://127.0.0.1:8000
      FRONTEND_URL: http://127.0.0.1:8001
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - ./:/var/www/html
      - backend_vendor:/var/www/html/vendor
    tty: true
    stdin_open: true

volumes:
  backend_vendor:
